### ISSUE TITLE
Decide on what main channel are we using 

### ISSUE THREAD

**Issue by serejandmyself** [synergislab/edu#11]
We have:

Telegram
Telegram channel
ETC

**Comment by didbit** [comment]
Как этим пользоваться))??

**Comment by serejandmyself** [comment]
> Как этим пользоваться))??

Нужно чтобы всех сделали members

**Comment by didbit** [comment]
Получается, что все могут смотреть наше общение тут?

**Comment by serejandmyself** [comment]
> Получается, что все могут смотреть наше общение тут?

Все верно. open source
